apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  labels:
    app: project
  name: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: project
  name: projectsvc
  namespace: project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9376
  selector:
    app: project
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: project
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 0
  desiredReplicas: 0
